//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Buena_Farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaVenta3
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public string Empleado { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public string Tarjeta { get; set; }
    }
}
