//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Buena_Farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaEmpleados
    {
        public int ID_de_empleado { get; set; }
        public string Nombre_completo { get; set; }
        public string Rol { get; set; }
        public string Estado { get; set; }
        public decimal Salario { get; set; }
        public string Contraseña { get; set; }
    }
}
