//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Buena_Farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaProductos
    {
        public int ID_del_producto { get; set; }
        public string Nombre_del_producto { get; set; }
        public int Cantidad_disponible { get; set; }
        public int idCategoria { get; set; }
        public decimal Precio { get; set; }
    }
}
